config/routes.rb
Rails.application.routes.draw do
  resources :wikis do
    resources :collaborators, only: [:new, :create, :update, :destroy]
  end

  devise_for :users
  get 'about' => 'welcome#about'

  root 'welcome#index'

  resources :users do
    member do
      get :confirm_email
    end
  end

  resources :charges, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  before_create :set_default_role

  has_many :wikis, dependent: :destroy
  has_many :collaborators, dependent: :destroy
  has_many :shared_wikis, through: :collaborators, source: :wiki

  before_save {if self.role == :standard then :amount end}

  enum role: [:standard, :premium, :admin]

  enum amount: [15.00]

  def set_default_role
    self.role = :standard
  end

  def collaborator?(wiki)
    self.collaborators.where(wiki: wiki).present?
  end


end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators

  def public?
    !private
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  
  protect_from_forgery with: :exception

  protect_from_forgery with: Pundit

  before_action :authenticate_user!

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def create
     # Creates a Stripe Customer object, for associating
     # with the charge
     customer = Stripe::Customer.create(
       email: current_user.email,
       card: params[:stripeToken]
     )

     # Where the real magic happens
     charge = Stripe::Charge.create(
       customer: customer.id, # Note -- this is NOT the user_id in your app
       amount: 15.00,
       description: "Upgrade to Premium Membership - #{current_user.email}",
       currency: 'usd'
     )

     @user.update_attributes(role: 'premium')
     #@user.role = 'premium'
     #@user.save

     flash[:notice] = "Thanks for all the money, #{current_user.email}! You can now create and edit private wikis."
     redirect_to user_path(current_user) # or wherever

     # Stripe will send back CardErrors, with friendly messages
     # when something goes wrong.
     # This `rescue block` catches and displays those errors.
     rescue Stripe::CardError => e
       flash[:alert] = e.message
       redirect_to new_charge_path
   end

   def new
   @stripe_btn_data = {
     key: "#{ Rails.configuration
     .stripe[:publishable_key] }",
     description: "Premium Membership - #{current_user.email}",
     amount: 15_00
   }
 end

 private

  def upgrade_user_role
    @user.role = 'premium'
  end

 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = Wiki.all
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create

     @wiki = Wiki.new
     @wiki.title = params[:wiki][:title]
     @wiki.body = params[:wiki][:body]
     @wiki.user = current_user

     if @wiki.save

       flash[:notice] = "Wiki was saved."
       redirect_to @wiki
     else

       flash.now[:alert] = "There was an error saving the wiki. Please try again."
       render :new
     end
   end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
     @wiki = Wiki.find(params[:id])
     @wiki.title = params[:wiki][:title]
     @wiki.body = params[:wiki][:body]

     if @wiki.save
       flash[:notice] = "Wiki was updated."
       redirect_to @wiki
     else
       flash.now[:alert] = "There was an error saving the Wiki. Please try again."
       render :edit
     end
   end

   def destroy
     @wiki = Wiki.find(params[:id])

     if @wiki.destroy
       flash[:notice] = "'#{@wiki.title}' was deleted successfully."
       redirect_to wikis_path
     else
       flash.now[:alert] = "There was an error deleting the wiki."
       render :show
     end
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    require 'redcarpet'
    renderer = Redcarpet::Render::HTML.new
    extensions = { :autolink => true }
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(text).html_safe
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
   <h4> Upgrade to Premium Membership </h4>
   <div>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
  </div>
 <% end %>

app/views/collaborators/_collaborators.html.erb
<div class="row">
  <div class="col-md-8">
    <h4>Collaborators</h4>
    <% wiki.collaborators.each do |collab| %>
      <h4><span class="glyphicon glyphicon-user" aria-hidden="true"> <%= collab.user.name %> <%= link_to "Remove", [wiki, collab], method: :delete, class: 'btn btn-sm btn-danger', data: { confirm: 'Are you sure you want to remove this user?'} if current_user.id == wiki.user_id || current_user.admin?%></span></h4>
    <% end %>
    <% if current_user.id == wiki.user_id || current_user.admin? %>
      <%= render partial: 'collaborators/form', locals: { wiki: wiki, collaborator: collaborator } %>
    <% end %>
  </div>
</div> 

app/views/collaborators/_form.html.erb
<%= form_tag [wiki, collaborator] do %>
  <div class="form-group">
    <%= text_field_tag :search, params[:search], class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= submit_tag "Add User", class: 'btn btn-warning' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Blocipedia", root_path %></li>
        <li><%= link_to "About", about_path %></li>

    <div class="pull-right user-info">
    <% if user_signed_in? %>
   Signed in as: <strong><%= current_user.email %></strong> |
   <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
   <%= link_to "Logout", destroy_user_session_path, method: :delete %> |

   <% if current_user.standard? %>
        <%= link_to "Upgrade to Premium", new_charge_path %>
   <% else %>
        <%= link_to "Downgrade to Standard", edit_user_registration_path %>
   <% end %>

   <% else %>
   <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
   <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
   <% end %>
  </div>
</ul>

<% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
<% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
<% end %>

<%= yield %>

  </body>
</html>

app/views/welcome/about.html.erb
<h1>Stay Tuned</h1>
<p>Blocipedia is a masterpiece in progress. Check back later for more features!</p>

app/views/welcome/index.html.erb
<h1>Welcome to index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/wikis/_form.html.erb
     <%= form_for wiki do |f| %>
     <% if @wiki.errors.any? %>

      <div class="alert alert-danger">

      <h4><%= pluralize(@wiki.errors.count, "error") %>.</h4>
      <ul>
        <% @wiki.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      </div>
      <% end %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
       </div>
       <% if current_user.premium? %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private wiki
          <% end %>
        </div>

        <div>
        <p>Add Collaborators</p>
        <% if current_user.id == @wiki.user_id || current_user.admin? %>
          <%= collection_check_boxes(:wiki, :user_ids, User.all, :id, :name) do |b| %>
            <%= b.check_box %>
            <%= b.label %><br />
          <% end %>
        <% end %>
      </div>

      <% end %>

       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

 <div class="row">
   <div class="col-md-8">
     <%= render partial: "form", locals: {wiki: @wiki} %>
   </div>
 </div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>

<div class="New Form">
  <%= link_to "New Post", new_wiki_path %>
</div>
<% @wikis.each do |wiki| %>
<div class="media">
   <div class="media-body">
     <% if wiki.private? %>
     <%= link_to wiki.title, wiki, class: "private" %> <small>[private]</small>
     <% else %>

     <%= link_to wiki.title, wiki %>
     <% end %>
      </h3>
      <small>By <%= wiki.user.name %> | <%= time_ago_in_words(wiki.created_at) %> ago</small>
     <h4 class="media-heading"><%= link_to markdown(wiki.title), wiki %></h4>
   </div>
 </div>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-8">
    <%= render partial: "form", locals: {wiki: @wiki} %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= markdown(@wiki.title) %></h1>
<small>
  Submitted <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.user.name %> <br>
</small>
<div class="row">
   <div class="col-md-8">
     <p><%= markdown(@wiki.body) %></p>
   </div>
 <div class="col-md-4">
   <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
 <!-- #9 -->
   <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
   </div>
 </div>